name: rtmp_player
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vlc_player: ^7.4.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
